=== senbox-org/CDSE-Copernicus-DEM-downloader/cdse-copernicus-dem-downloader/configuration/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DEM_DOWNLOADER_CONFIGURATION_FILE">
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="DEM_Option"/>
			</xs:sequence>
		</xs:complexType>
    </xs:element>
    <xs:element name="DEM_Option">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Resolution"/>
                <xs:element ref="Collection"/>
				<xs:element ref="Elevation_Model"/>
				<xs:element ref="Tiles_Input_File"/>
				<xs:element ref="DEM_Output_Directory"/>
            </xs:sequence>
        </xs:complexType>
	</xs:element>
    <xs:element name="Resolution">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="DEFAULT"/>
				<xs:enumeration value="90"/>
				<xs:enumeration value="30"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
    <xs:element name="Collection">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="COP-DEM"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Elevation_Model">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="DEFAULT"/>
				<xs:enumeration value="DGED"/>
				<xs:enumeration value="DTED"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tiles_Input_File">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DEM_Output_Directory">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== senbox-org/CDSE-Copernicus-DEM-downloader/cdse-copernicus-dem-downloader/configuration/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<DEM_DOWNLOADER_CONFIGURATION_FILE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
    <DEM_Option>
        <!-- Collection, Resolution and Elevation Model will determine the server path for the DEM Retrieval-->
        <!-- Default is COP-DEM-90-DGED-->
        <Collection>CCM</Collection>
        <Delivery_Id>2024_1</Delivery_Id>
        <Resolution>90</Resolution>
        <Elevation_Model>DGED</Elevation_Model>
         <!-- Full path to the list of tiles. Tool's Input_Tiles.txt is used if DEFAULT-->
         <Tiles_Input_File>DEFAULT</Tiles_Input_File>
        <!-- Full path to the Sen2Cor DEM Directory. Tool's Output_Dir is used if DEFAULT-->
        <DEM_Output_Directory>DEFAULT</DEM_Output_Directory>
    </DEM_Option>
</DEM_DOWNLOADER_CONFIGURATION_FILE>
